<?php $developer = $this->developer; ?>
<div class="row">
    <ol class="breadcrumb">
        <li><a href="/">Listado de desarrolladores</a></li>
        <li>Desarrollador</li>
        <li><?php echo $developer->getName(); ?></li>
    </ol>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="row">
            <div class="col-md-2">
                <span class="glyphicon glyphicon-user" aria-hidden="true" style="font-size:50px;"></span>
                <span class="glyphicon glyphicon-globe" style="color:<?php echo ($developer->getIsOnline())?'green':'red'; ?>" aria-hidden="true" style="font-size:50px;"></span>
            </div>
            <div class="col-md-10">
                <h5 class="card-title"><b><?php echo $developer->getName(); ?></b></h5>
                <h6 class="card-subtitle"><b><?php echo $developer->getEmail(); ?></b></h6>
                <p class="card-text">
                    <ul>
                        <li><b>Telefono:</b><?php echo $developer->getPhone(); ?></li>
                        <li><b>Dirección:</b><?php echo $developer->getAddress(); ?></li>
                        <li><b>Posición:</b><?php echo $developer->getPosition(); ?></li>
                        <li><b>Salario:</b><?php echo $developer->getSalary(); ?></li>
                        <li><b>Habilidades:</b></li>
                    </ul>
                    <?php foreach ($developer->getSkills() as $skill): ?>
                        <span class="label label-primary" style="font-size:16px;"><?php echo $skill['skill']; ?></span>
                    <?php endforeach; ?>
                </p>
            </div>
        </div>
    </div>
</div>
