<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost:2020/soap/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="MyDeveloperService" targetNamespace="http://localhost:2020/soap/wsdl"><types><xsd:schema targetNamespace="http://localhost:2020/soap/wsdl"/></types><portType name="MyDeveloperServicePort"/><binding name="MyDeveloperServiceBinding" type="tns:MyDeveloperServicePort"><soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/></binding><service name="MyDeveloperServiceService"><port name="MyDeveloperServicePort" binding="tns:MyDeveloperServiceBinding"><soap:address location="http://localhost:2020/soap/wsdl"/></port></service></definitions>
